### ISSUE TITLE
Code copy button

### ISSUE THREAD

**Issue by rob-at-cortex** [AirWalk-Digital/airview-next#3]
Add a button to copy code
https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/132

**Comment by f-steel** [comment]
Seems like the above issue was never resolved. Perhaps https://github.com/nkbt/react-copy-to-clipboard could work

**Comment by f-steel** [comment]
<strike> https://github.com/AirWalk-Digital/airview-next/pull/49 possible solution </strike>

Now merged
