### ISSUE TITLE
Implement the /resourcing functionality

### ISSUE THREAD

**Issue by rob-at-cortex** [AirWalk-Digital/airview-next#42]
/resourcing needs to be moved into the TypeScript (beta branch) version.

**Comment by f-steel** [comment]
started making some progress on this (with stashed changes) but there is quite a lot to change to align it with TS

**Comment by f-steel** [comment]
Have created new repo https://github.com/AirWalk-Digital/airwalk-resourcing with much of the content from this repo removed
