### ISSUE TITLE
Scrolling bug on the editor

### ISSUE THREAD

**Issue by rob-at-cortex** [AirWalk-Digital/airview-next#58]
example: https://mdx.airview.preprod.airwalkconsulting.io/docs/edit/feature%2FAI-Project-Documentation/services/aws_dynamodb/_index.md

when you're editing in the markdown view (far right icon), the scrolling doesn't work

**Comment by f-steel** [comment]
to me this more looks like an issue with mdxeditor as doesn't appear to have css applied from this repo

**Comment by rob-at-cortex** [comment]
I *think* we should be able to change the css within the editor.. like using the existing Styled component ?
like here: https://github.com/AirWalk-Digital/airview-next/blob/38f71d1c1b5f4a4565999f1734d529ba89024236/src/_components/Editor/Editor.tsx#L149

**Comment by f-steel** [comment]
ahhh I see the problem, when the diff mode is activate the rich-text-editor display is set to the 'none' and the diff editor is then rendered underneath. Have added the require css to the diff part now
https://github.com/AirWalk-Digital/airview-next/pull/72

**Comment by f-steel** [comment]
https://github.com/AirWalk-Digital/airview-next/pull/72
