### ISSUE TITLE
save favourite branches

### ISSUE THREAD

**Issue by rob-at-cortex** [AirWalk-Digital/airview-next#60]
in the editor, when you select a branch, there are a lot of them and it's hard to find the one you wanted..
we need a way of "saving" the ones that the user has used or created, and putting those at the top.
when the branch doesn't exist, we need to not show it (obviously)

so if you navigate to a page, add that to the list of branches in a cookie?
when you click the drop down to select the branch, these should be at the top. the default branch for the repo should always be at the top. this is saved in the site.config.json file
when we click the drop down, also clean up the cookie to remove branches that no longer exist?

**Comment by f-steel** [comment]
https://github.com/AirWalk-Digital/airview-next/pull/62 implemented possible fix
