### ISSUE TITLE
Editor is blank

### ISSUE THREAD

**Issue by rob-at-cortex** [AirWalk-Digital/airview-next#61]
this may be just in preprod, but as an example, 
https://mdx.airview.preprod.airwalkconsulting.io/docs/edit/feature%2FAI-Project-Documentation/services/aws_dynamodb/_index.md

I edited this page, pressed save. then the editor goes blank. refreshing the page, it's still blank, even though the correct content is returned from the API (it must have saved properly)

maybe something to do with the websockets collaboration? I dont think we have that in prepared yet, so maybe a failure of that causes the editor to misbehave a bit

**Comment by f-steel** [comment]
looks to be the websockets yeah, not sure if the new command is included in the pipeline? Was struggling to see where all of that takes place
